In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
training_set = pd.read_csv("./dataset/training_set.csv")

In [5]:
training_set.groupby(["CODE_GENDER"]).agg({"TARGET": ["count", "mean"]})

             TARGET
              count      mean
CODE_GENDER
F            161978  0.070084
M             84028  0.101347
XNA               3  0.000000

In [6]:
df = training_set.copy()

In [7]:
df["CODE_GENDER"] = (df["CODE_GENDER"] == "F").astype(int)

In [8]:
df.groupby(["CODE_GENDER"]).agg({"TARGET": ["count", "mean"]})

             TARGET
              count      mean
CODE_GENDER
0             84031  0.101344
1            161978  0.070084

In [9]:
df["FLAG_OWN_CAR"] = (df["FLAG_OWN_CAR"]=="Y").astype(int)
df["FLAG_OWN_REALTY"] = (df["FLAG_OWN_REALTY"]=="Y").astype(int)

In [41]:
training_set.groupby(["FLAG_DOCUMENT_3"]).agg({"TARGET": ["count", "mean"]})

                 TARGET
                  count      mean
FLAG_DOCUMENT_3
0                 71337  0.061875
1                174672  0.088474

In [13]:
training_set.groupby(["REG_CITY_NOT_LIVE_CITY"]).agg({"SK_ID_CURR": "count", "TARGET": "mean"})

                        SK_ID_CURR    TARGET
REG_CITY_NOT_LIVE_CITY
0                           226728  0.077238
1                            19281  0.122193

In [14]:
training_set["REGION_RATING_CLIENT_W_CITY"]

0         1
1         2
2         2
3         3
4         2
         ..
246004    2
246005    2
246006    2
246007    2
246008    2
Name: REGION_RATING_CLIENT_W_CITY, Length: 246009, dtype: int64

In [15]:
training_set.groupby(["REGION_RATING_CLIENT_W_CITY"]).agg({"SK_ID_CURR": "count", "TARGET": "mean"})

                             SK_ID_CURR    TARGET
REGION_RATING_CLIENT_W_CITY
1                                 27192  0.048249
2                                183797  0.079174
3                                 35020  0.114335

In [40]:
list(df.columns)

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR',
 'AGE',
 'EXT_SOURCE_MEAN',
 'REGION_POPULATION_RANK']

In [41]:
df.groupby(["NAME_EDUCATION_TYPE"]).agg({"TARGET": ["count", "mean"]})

                               TARGET
                                count      mean
NAME_EDUCATION_TYPE
Academic degree                   137  0.021898
Higher education                59903  0.053403
Incomplete higher                8204  0.086177
Lower secondary                  3043  0.112060
Secondary / secondary special  174722  0.089388

In [42]:
mapping_education_type = {
    'Lower secondary': 0,
    'Secondary / secondary special': 1,
    'Incomplete higher': 2,
    'Higher education': 3,
    'Academic degree': 4
}

def preprocess_education_type(input_str):
    return mapping_education_type[input_str]

In [43]:
df["NAME_EDUCATION_TYPE"] = df["NAME_EDUCATION_TYPE"].apply(preprocess_education_type)

In [44]:
df.groupby(["NAME_EDUCATION_TYPE"]).agg({"TARGET": ["count", "mean"]})

                     TARGET
                      count      mean
NAME_EDUCATION_TYPE
0                      3043  0.112060
1                    174722  0.089388
2                      8204  0.086177
3                     59903  0.053403
4                       137  0.021898

In [48]:
df.groupby(["NAME_INCOME_TYPE"]).agg({"TARGET": ["count", "mean"]})

                      TARGET
                       count      mean
NAME_INCOME_TYPE
Businessman                7  0.000000
Commercial associate   57256  0.075241
Maternity leave            2  0.000000
Pensioner              44336  0.054200
State servant          17410  0.057611
Student                   14  0.000000
Unemployed                17  0.411765
Working               126967  0.095671

In [59]:
df["NAME_INCOME_TYPE_COM"] = (df["NAME_INCOME_TYPE"] == "Commercial associate").astype(int)
df["NAME_INCOME_TYPE_PEN"] = (df["NAME_INCOME_TYPE"] == "Pensioner").astype(int)
df["NAME_INCOME_TYPE_STA"] = (df["NAME_INCOME_TYPE"] == "State servant").astype(int)
df["NAME_INCOME_TYPE_WOR"] = (df["NAME_INCOME_TYPE"] == "Working").astype(int)

In [71]:
df["DAYS_BIRTH"] = (df["DAYS_BIRTH"] / 365).astype(int).abs()

In [73]:
df.groupby((df["DAYS_BIRTH"] / 10).astype(int)).agg({"TARGET": ["count", "mean"]})

           TARGET
            count      mean
DAYS_BIRTH
2           36036  0.115634
3           65947  0.095122
4           61146  0.076178
5           54309  0.061702
6           28571  0.049666

In [23]:
mapping_education_type = {
    'Lower secondary': 0,
    'Secondary / secondary special': 1,
    'Incomplete higher': 2,
    'Higher education': 3,
    'Academic degree': 4
}

def preprocess_education_type(input_str):
    return mapping_education_type[input_str]

def preprocess(dataset):
    df = dataset.copy()
    # gender
    df["CODE_GENDER"] = (df["CODE_GENDER"] == "F").astype(int)
    # car
    df["FLAG_OWN_CAR"] = (df["FLAG_OWN_CAR"]=="Y").astype(int)
    # realty
    df["FLAG_OWN_REALTY"] = (df["FLAG_OWN_REALTY"]=="Y").astype(int)
    # education
    df["NAME_EDUCATION_TYPE"] = df["NAME_EDUCATION_TYPE"].apply(preprocess_education_type)
    # income type
    df["NAME_INCOME_TYPE_COM"] = (df["NAME_INCOME_TYPE"] == "Commercial associate").astype(int)
    df["NAME_INCOME_TYPE_PEN"] = (df["NAME_INCOME_TYPE"] == "Pensioner").astype(int)
    df["NAME_INCOME_TYPE_STA"] = (df["NAME_INCOME_TYPE"] == "State servant").astype(int)
    df["NAME_INCOME_TYPE_WOR"] = (df["NAME_INCOME_TYPE"] == "Working").astype(int)
    # age
    df["DAYS_BIRTH"] = (df["DAYS_BIRTH"] / 365).astype(int).abs()

    return df

In [24]:
bureau = pd.read_csv("bureau.csv")
bureau = bureau.groupby(["SK_ID_CURR"], as_index=False).agg({"CREDIT_DAY_OVERDUE": "max"})

In [25]:
training_set = pd.read_csv("./dataset/training_set.csv")
validation_set = pd.read_csv("./dataset/validation_set.csv")
testing_set = pd.read_csv("./dataset/testing_set.csv")

In [26]:
training_set = preprocess(training_set)
validation_set = preprocess(validation_set)
testing_set = preprocess(testing_set)

In [27]:
training_set = pd.merge(training_set, bureau, on=["SK_ID_CURR"], how="left").fillna({"CREDIT_DAY_OVERDUE": 0})
validation_set = pd.merge(validation_set, bureau, on=["SK_ID_CURR"], how="left").fillna({"CREDIT_DAY_OVERDUE": 0})
testing_set = pd.merge(testing_set, bureau, on=["SK_ID_CURR"], how="left").fillna({"CREDIT_DAY_OVERDUE": 0})

In [38]:
used_columns = ['SK_ID_CURR', 'TARGET', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
                'NAME_EDUCATION_TYPE', 'NAME_INCOME_TYPE_COM', 'NAME_INCOME_TYPE_PEN',
                'NAME_INCOME_TYPE_STA', 'NAME_INCOME_TYPE_WOR', 'DAYS_BIRTH',
                'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY','FLAG_EMP_PHONE', 
               'REG_CITY_NOT_LIVE_CITY', 'REGION_RATING_CLIENT_W_CITY'  ]

In [39]:
training_set = training_set.fillna({"AMT_ANNUITY": 0})
validation_set = validation_set.fillna({"AMT_ANNUITY": 0})
testing_set = testing_set.fillna({"AMT_ANNUITY": 0})

In [40]:
training_set[used_columns].to_csv("./dataset/final/training_set.csv", index=False)
validation_set[used_columns].to_csv("./dataset/final/validation_set.csv", index=False)
testing_set[used_columns].to_csv("./dataset/final/testing_set.csv", index=False)